//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MojeDane")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="MojeDane", IsNullable=false)]
public partial class ListaStudentow {
    
    private ListaStudentowStudent[] studentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Student")]
    public ListaStudentowStudent[] Student {
        get {
            return this.studentField;
        }
        set {
            this.studentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MojeDane")]
public partial class ListaStudentowStudent {
    
    private string imieField;
    
    private string nazwiskoField;
    
    private System.DateTime dataUrField;
    
    private ListaStudentowStudentAdresy adresyField;
    
    private ListaStudentowStudentPrzedmiot[] zajeciaField;
    
    /// <remarks/>
    public string Imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <remarks/>
    public string Nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataUr {
        get {
            return this.dataUrField;
        }
        set {
            this.dataUrField = value;
        }
    }
    
    /// <remarks/>
    public ListaStudentowStudentAdresy Adresy {
        get {
            return this.adresyField;
        }
        set {
            this.adresyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Przedmiot", IsNullable=false)]
    public ListaStudentowStudentPrzedmiot[] Zajecia {
        get {
            return this.zajeciaField;
        }
        set {
            this.zajeciaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MojeDane")]
public partial class ListaStudentowStudentAdresy {
    
    private string adresStalyField;
    
    private string adresTymczasowyField;
    
    /// <remarks/>
    public string AdresStaly {
        get {
            return this.adresStalyField;
        }
        set {
            this.adresStalyField = value;
        }
    }
    
    /// <remarks/>
    public string AdresTymczasowy {
        get {
            return this.adresTymczasowyField;
        }
        set {
            this.adresTymczasowyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="MojeDane")]
public partial class ListaStudentowStudentPrzedmiot {
    
    private string nazwaField;
    
    private string[] ocenyField;
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Ocena", IsNullable=false)]
    public string[] Oceny {
        get {
            return this.ocenyField;
        }
        set {
            this.ocenyField = value;
        }
    }
}
